import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import mongoSanitize from 'express-mongo-sanitize';
import { loadEnv } from './config/env.js';
import connectDB from './config/db.js';
import startupSeed from './services/startupSeed.js';
import { notFound, errorHandler } from './middleware/errorHandler.js';

import authRoutes from './routes/authRoutes.js';
import courseRoutes from './routes/courseRoutes.js';
import internshipRoutes from './routes/internshipRoutes.js';
import paymentRoutes from './routes/paymentRoutes.js';
import certificateRoutes from './routes/certificateRoutes.js';
import paymentSettingsRoutes from './routes/paymentSettingsRoutes.js';
import applicationRoutes from './routes/applicationRoutes.js';
import contactRoutes from './routes/contactRoutes.js';
import recommendationRoutes from './routes/recommendationRoutes.js';
import documentRoutes from './routes/documentRoutes.js';
import noteRoutes from './routes/noteRoutes.js';
import projectRoutes from './routes/projectRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import { autoGenerateDueCertificates } from './services/certificateService.js';
import { isSupabaseConfigured } from './config/supabase.js';
import { isGoogleDriveConfigured } from './services/googleDriveService.js';

loadEnv();

if (process.env.NODE_ENV === 'production') {
  const secret = process.env.JWT_SECRET || '';
  if (secret.length < 32 || /your_super_secret|changeme|example/i.test(secret)) {
    console.error('FATAL: Set a strong JWT_SECRET (32+ characters) before production deployment.');
    process.exit(1);
  }
}

await connectDB();
await startupSeed();

const emailProvider = (() => {
  const smtp = process.env.SMTP_USER;
  const isPlaceholder = (v) => !v || /your_|xxxxx|example\.com|changeme/i.test(String(v));
  if (smtp && !isPlaceholder(smtp)) return 'smtp';
  return 'mock';
})();

const app = express();
app.set("trust proxy", 1);

const allowedOrigins = (process.env.CLIENT_URL || 'http://localhost:5173')
  .split(',')
  .map((origin) => origin.trim())
  .filter(Boolean);

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 300,
  standardHeaders: true,
  legacyHeaders: false,
  message: { success: false, message: 'Too many requests, please try again later' },
});

app.use(helmet({
  crossOriginResourcePolicy: { policy: 'cross-origin' },
  contentSecurityPolicy: false,
}));
app.use(cors({
  origin: (origin, callback) => {
    if (!origin || allowedOrigins.includes(origin)) {
      callback(null, true);
      return;
    }
    callback(new Error('Not allowed by CORS'));
  },
  credentials: true,
}));
app.use(limiter);
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(mongoSanitize());
app.use('/uploads', express.static('uploads', { dotfiles: 'deny', index: false }));

app.get('/api/health', (req, res) => {
  res.json({ success: true, message: 'Campus Code Labs API is running', tagline: 'THINK. CODE. DELIVER.' });
});

app.use('/api/auth', authRoutes);
app.use('/api/courses', courseRoutes);
app.use('/api/internships', internshipRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/certificates', certificateRoutes);
app.use('/api/applications', applicationRoutes);
app.use('/api/contact', contactRoutes);
app.use('/api/notes', noteRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/recommendations', recommendationRoutes);
app.use('/api/payment-settings', paymentSettingsRoutes);
app.use('/api/admin', adminRoutes);

const runAutoCertificates = () => {
  autoGenerateDueCertificates()
    .then((results) => {
      if (results.length) console.log(`[Cron] Auto-generated ${results.length} certificate(s)`);
    })
    .catch((err) => console.error('[Cron] Auto-certificate error:', err.message));
};

setTimeout(runAutoCertificates, 30000);
setInterval(runAutoCertificates, 24 * 60 * 60 * 1000);

app.use(notFound);
app.use(errorHandler);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Campus Code Labs Server running on port ${PORT}`);
  console.log(`Email provider: ${emailProvider}${emailProvider === 'mock' ? ' (emails logged to console only)' : ''}`);
  console.log(`Storage: ${isSupabaseConfigured() ? 'supabase' : isGoogleDriveConfigured() ? 'google drive' : 'local uploads'}`);
});
