import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import connectDB from './config/db.js';
import { notFound, errorHandler } from './middleware/errorHandler.js';

import authRoutes from './routes/authRoutes.js';
import courseRoutes from './routes/courseRoutes.js';
import internshipRoutes from './routes/internshipRoutes.js';
import paymentRoutes from './routes/paymentRoutes.js';
import certificateRoutes from './routes/certificateRoutes.js';
import paymentSettingsRoutes from './routes/paymentSettingsRoutes.js';
import applicationRoutes from './routes/applicationRoutes.js';
import recommendationRoutes from './routes/recommendationRoutes.js';
import documentRoutes from './routes/documentRoutes.js';
import noteRoutes from './routes/noteRoutes.js';
import projectRoutes from './routes/projectRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import { razorpayWebhook } from './controllers/paymentController.js';
import { autoGenerateDueCertificates } from './services/certificateService.js';
import { isSupabaseConfigured } from './config/supabase.js';

dotenv.config();
connectDB();

const emailProvider = (() => {
  const smtp = process.env.SMTP_USER;
  const isPlaceholder = (v) => !v || /your_|xxxxx|example\.com|changeme/i.test(String(v));
  if (smtp && !isPlaceholder(smtp)) return 'smtp';
  return 'mock';
})();

const app = express();

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 200,
  message: { success: false, message: 'Too many requests, please try again later' },
});

app.use(cors({
  origin: process.env.CLIENT_URL || 'http://localhost:5173',
  credentials: true,
}));
app.use(limiter);

app.post('/api/payments/webhook', express.raw({ type: 'application/json' }), razorpayWebhook);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/uploads', express.static('uploads'));

app.get('/api/health', (req, res) => {
  res.json({ success: true, message: 'Learnovate API is running', tagline: 'Innovation Through Learning' });
});

app.use('/api/auth', authRoutes);
app.use('/api/courses', courseRoutes);
app.use('/api/internships', internshipRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/certificates', certificateRoutes);
app.use('/api/applications', applicationRoutes);
app.use('/api/notes', noteRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/recommendations', recommendationRoutes);
app.use('/api/payment-settings', paymentSettingsRoutes);
app.use('/api/admin', adminRoutes);

const runAutoCertificates = () => {
  autoGenerateDueCertificates()
    .then((results) => {
      if (results.length) console.log(`[Cron] Auto-generated ${results.length} certificate(s)`);
    })
    .catch((err) => console.error('[Cron] Auto-certificate error:', err.message));
};

setTimeout(runAutoCertificates, 30000);
setInterval(runAutoCertificates, 24 * 60 * 60 * 1000);

app.use(notFound);
app.use(errorHandler);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Learnovate Server running on port ${PORT}`);
  console.log(`Email provider: ${emailProvider}${emailProvider === 'mock' ? ' (emails logged to console only)' : ''}`);
  console.log(`Storage: ${isSupabaseConfigured() ? 'supabase' : 'local uploads'}`);
});
