import Certificate from '../models/Certificate.js';
import Internship from '../models/Internship.js';
import Course from '../models/Course.js';
import User from '../models/User.js';
import { generateCertificateId } from '../utils/generateId.js';
import { generateCertificatePDF } from './pdfService.js';
import { uploadBuffer, uploadImageBuffer } from './storageService.js';
import QRCode from 'qrcode';
import { sendCertificateEmail } from './emailService.js';

export const issueCertificateForInternship = async (internship, user, { sendEmail = true } = {}) => {
  if (internship.certificate) {
    const existing = await Certificate.findById(internship.certificate);
    if (existing) return existing;
  }

  const course = await Course.findById(internship.course._id || internship.course);
  const student = user._id ? user : await User.findById(internship.user);
  const certificateId = generateCertificateId();
  const verifyUrl = `${process.env.CLIENT_URL}/verify/${certificateId}`;
  const issueDate = new Date();

  const pdfBuffer = await generateCertificatePDF({
    studentName: student.fullName,
    courseName: course.title,
    internshipId: internship.internshipId,
    duration: internship.duration,
    certificateId,
    issueDate,
    verifyUrl,
  });

  let certificateUrl = '';
  let qrCodeUrl = '';

  try {
    const certUpload = await uploadBuffer(pdfBuffer, 'certificates', `${certificateId}.pdf`, 'application/pdf');
    certificateUrl = certUpload.url;

    const qrBuffer = await QRCode.toBuffer(verifyUrl, { width: 300 });
    const qrUpload = await uploadBuffer(qrBuffer, 'certificates', `${certificateId}-qr.png`, 'image/png');
    qrCodeUrl = qrUpload.url;
  } catch (err) {
    console.error('Certificate upload error:', err.message);
    certificateUrl = verifyUrl;
  }

  const certificate = await Certificate.create({
    certificateId,
    user: student._id,
    internship: internship._id,
    course: course._id,
    studentName: student.fullName,
    courseName: course.title,
    duration: internship.duration,
    completionDate: issueDate,
    certificateUrl,
    qrCodeUrl,
  });

  internship.certificate = certificate._id;
  if (internship.status === 'active') internship.status = 'completed';
  await internship.save();

  if (sendEmail) {
    await sendCertificateEmail(student, certificate, certificateUrl).catch(console.error);
  }

  return certificate;
};

export const autoGenerateDueCertificates = async () => {
  const now = new Date();
  const inThreeDays = new Date();
  inThreeDays.setDate(inThreeDays.getDate() + 3);

  const internships = await Internship.find({
    status: 'active',
    $or: [{ certificate: null }, { certificate: { $exists: false } }],
    endDate: { $lte: inThreeDays },
  }).populate('user');

  const results = [];
  for (const internship of internships) {
    try {
      const cert = await issueCertificateForInternship(internship, internship.user, { sendEmail: true });
      results.push({ internshipId: internship.internshipId, certificateId: cert.certificateId });
    } catch (err) {
      console.error(`Auto-cert failed for ${internship.internshipId}:`, err.message);
    }
  }
  return results;
};
